---
title: "Variable Stars - Histogram of differences"
author: "Roberto Maestre"
date: "11/15/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(variableStars)
library(data.table)
library(ggplot2)
library(microbenchmark)
```


### Data from a pulsar star

In this case, we use the photometry of a pulsar star, in which timestamp the magnitude of the pulsar is given. In this case, analize the patter in visually complex.

```{r pulsar}
## noisy signal with amplitude modulation
x <- seq(from = 0,
         to = 100,
         by = 5)
# Add secuential times
dt.test <-
  data.frame("time" = seq(from = 1, to = length(x)), "x" = x)
ggplot(aes(time, x), data = dt.test) +
  geom_point() +
  geom_line() +
  theme_bw()
```

We use DFT to calculate the amplitude in each frecuency.

```{r pulsarSpectrum, warning=F}
res <- go(dt.test$time, dt.test$x, "uniform", 0.1)

# Plot frecuency and amplitude
plot(res$frequency, res$amplitude)


plot(res$resHist$histogram$bins, res$resHist$histogram$values)
```
