---
title: "Variable Stars - Main workflow with simple synthetic data"
author: "Roberto Maestre"
date: "11/16/2018"
output: github_document
vignette: >
  %\VignetteEngine{knitr::rmarkdown}	  %\VignetteEngine{knitr::knitr}
  %\VignetteIndexEntry{Using captioner}	  %\VignetteIndexEntry{Using captioner}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(variableStars)
library(data.table)
library(ggplot2)
library(microbenchmark)
```


### Synthetic data generation representing photometry

This first example is used to check the main procedure workflow results.

```{r dataGeneration}
# Linear space with equal separation
x <- sin(seq(from = 0,
         to = 100,
         by = 5))
# Add secuential times
dt.test <-
  data.frame("time" = seq(from = 1, to = length(x)), "mmag" = x)

# Plot
ggplot(aes(time, mmag), data = dt.test) +
  geom_point() +
  geom_line() +
  theme_bw()
```

Calculate amplitures by FT

```{r calculateEspectrum, warning=F}
# Calculate amplitudes and frequence
dt.spectrum <- calculate_amplitudes(dt.test$time, dt.test$mmag)
# Plot amplitudes
plot_spectrum(-0.5, 0.5, dt.spectrum)
# Save data
# Save DF to disk
write.table(dt.spectrum[c("frequency", "amplitude")], file = "/tmp/data.csv", 
          sep = "\t",
          quote = F, 
          row.names = F, 
          col.names = F)
```


Main procedure call

```{r calculate, warning=F}
out <- go(dt.spectrum$frequency,
          dt.spectrum$amplitude,
          filter = "uniform",
          gRegimen = 0,
          numFrequencies = 0)
```

#### Fourier Transform on the photometry data

```{r ftPhotometry, warning=F}
# Plot frecuency and amplitude
ggplot(aes(x = frequency, y = amplitude), data = data.frame(out$photometry)) +
  geom_point() +
  geom_line() +
  ggtitle("FT on the photometry data") +
  theme_bw()
```


```{r ftPower, warning=F}
# Plot frecuency and amplitude
dt <-
  data.frame("f" = out$ft$f,
             "powerSpectrum" = out$ft$powerSpectrum)
ggplot(aes(x = f, y = powerSpectrum), data = dt) +
  geom_point() +
  geom_line() +
  ggtitle("FT - Object method. Power Spectrum") +
  theme_bw()
```

```{r ftPowerInverse, warning=F}
# Plot frecuency and amplitude
ggplot(
  aes(x = f, y = powerSpectrum),
  data = data.frame(
    "f" = out$ft$f,
    "powerSpectrum" = out$ft$powerSpectrumInverse
  )
) +
  geom_point() +
  geom_line() +
  ggtitle("FT - Object method. Inverse power Spectrum") +
  theme_bw()
```



```{r diffsHistogram, warning=F}
dt <- data.frame(out$diff$diffHistogram$histogram)
ggplot(aes(x = bins, y = values), data = dt[dt$values > 0, ]) +
  geom_bar(stat = "identity") +
  ggtitle("Histogram of differences") +
  theme_bw()
```


