# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

seq_int <- function(first, last) {
    .Call(`_variableStars_seq_int`, first, last)
}

seq_rev <- function(x) {
    .Call(`_variableStars_seq_rev`, x)
}

compute_fft <- function(x) {
    .Call(`_variableStars_compute_fft`, x)
}

calculate_amplitudes <- function(time, x) {
    .Call(`_variableStars_calculate_amplitudes`, time, x)
}

apodization <- function(frequences, filter) {
    .Call(`_variableStars_apodization`, frequences, filter)
}

differences <- function(frequences) {
    .Call(`_variableStars_differences`, frequences)
}

diffHistogram <- function(frequences, dnu) {
    .Call(`_variableStars_diffHistogram`, frequences, dnu)
}

